spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /account
#数据源
datasource:
              name: oracle
              driver-class-name: oracle.jdbc.OracleDriver
              url: jdbc:oracle:thin:@127.0.0.1:orcl
              username: test
              password: test
  hikari:
    minimum-idle: 5
    maximum-pool-size: 15
    connection-test-query: select 1 from dual
    max-lifetime: 1800000
    connection-timeout: 30000
    pool-name: DatebookHikariCP
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
#配置日志
logging:
  #配置日志文件路径
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
  file:
    path: D:\reserach\reserachLog.log
  pattern:
    console: %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
    file: %d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n

