server:
  port: 8090
  tomcat.max-threads: 10
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /account
    session:
      timeout: 1200   #设置session超时时间为20分钟
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: HTML
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account_book?serverTimezone=UTC
    username: root
    password: root123456
  redis:
    # Redis服务器连接密码（默认为空）
    password: root123456
    database: 0
    port: 6379
    host: 192.168.0.24
    timeout: 1000
    jedis:
      pool:
        max-idle: 10
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        max-wait: -1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.home.account.entity
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
    # 使用druid数据源

hikari:
  minimum-idle: 5
  # 空闲连接存活最大时间，默认600000（10分钟）
  idle-timeout: 180000
  # 连接池最大连接数，默认是10
  maximum-pool-size: 10
  # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
  auto-commit: true
  # 连接池名称
  pool-name: MyHikariCP
  # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
  max-lifetime: 1800000
  # 数据库连接超时时间,默认30秒，即30000
  connection-timeout: 30000
  connection-test-query: SELECT 1

elastic:
  clusterName: test-es-cluster
  ip1: 192.168.111.230
  ip2: 192.168.111.231
  ip3: 192.168.111.232
  ip4: 192.168.111.233
  port: 9300


logging:
  #配置日志文件路径
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
  file:
    path: D:\reserach\reserachLog
